name: Run Update Script on Push

on:
  push:
    branches:
      - main

jobs:
  run-update-script:
    runs-on: self-hosted
    steps:
      - name: Set HOME environment variable
        run: echo "Setting HOME variable"
        env:
          HOME: /root

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git for further authentication
        run: |
          git config --global user.email "62218284+vMohammad24@users.noreply.github.com"
          git config --global user.name "vMohammad24"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/vMohammad24/VOT.git

      - name: Run update script
        run: /root/update.sh
