name: Run Update Script on Push

on:
  push:
    branches:
      - main

jobs:
  run-update-script:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
        env:
          HOME: /root # Set HOME globally for this step
      - name: Print environment variables
        run: env

      - name: Set up Git for further authentication
        run: |
          git config --global user.email "62218284+vMohammad24@users.noreply.github.com"
          git config --global user.name "vMohammad24"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/vMohammad24/VOT.git
        env:
          HOME: /root # Set HOME for this step

      - name: Run update script
        run: /root/update.sh
        env:
          HOME: /root # Ensure HOME is set for this step
